### Local Routes
GET http://localhost:3000/
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/by/query?id=68d7489a59f220373be439f7
###
GET http://localhost:3000/contacts/by/query?id=68d7489a59f220373be439f8
###
GET http://localhost:3000/contacts/by/query?id=68d7489a59f220373be439f9
###
GET http://localhost:3000/contacts/68d7489a59f220373be439f7
###
GET http://localhost:3000/contacts/68d7489a59f220373be439f8
###
GET http://localhost:3000/contacts/68d7489a59f220373be439f9

###
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Hyrum",
  "lastName": "Whittier",
  "email": "whittierht@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "2000-09-10"
}

###
@id=

###
PUT http://localhost:3000/contacts/{{id}}
Content-Type: application/json

{
  "firstName": "Hyrum",
  "lastName": "Whittier",
  "email": "whi19050@byui.edu",
  "favoriteColor": "Green",
  "birthday": "2000-09-10"
}

###
DELETE http://localhost:3000/contacts/{{id}}



### Render Routes
GET https://three41-project-1r8q.onrender.com/
###
GET https://three41-project-1r8q.onrender.com/contacts
###
GET https://three41-project-1r8q.onrender.com/contacts/by/query?id=68d7489a59f220373be439f7
###
GET https://three41-project-1r8q.onrender.com/contacts/by/query?id=68d7489a59f220373be439f8
###
GET https://three41-project-1r8q.onrender.com/contacts/by/query?id=68d7489a59f220373be439f9
###
GET https://three41-project-1r8q.onrender.com/contacts/68d7489a59f220373be439f7
###
GET https://three41-project-1r8q.onrender.com/contacts/68d7489a59f220373be439f8
###
GET https://three41-project-1r8q.onrender.com/contacts/68d7489a59f220373be439f9

###
POST https://three41-project-1r8q.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Hyrum",
  "lastName": "Whittier",
  "email": "whittierht@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "2000-09-10"
}


###
PUT https://three41-project-1r8q.onrender.com/contacts/{{id}}
Content-Type: application/json

{
  "firstName": "Hyrum",
  "lastName": "Whittier",
  "email": "whi19050@byui.edu",
  "favoriteColor": "Green",
  "birthday": "2000-09-10"
}

###
DELETE https://three41-project-1r8q.onrender.com/contacts/{{id}}

###
http://localhost:3000/api-docs/